### PR TITLE
Fixes roles property and disables infinite loading

### LINKED ISSUE #76: Attribute slicer crashes because the "roles" property on DataViewMetadataColumns is optional
The "roles" property on columns is optional.  Occasionally PowerBI will send columns that are missing this property.  Attribute Slicer needs to account for this, specifically: [dataConversion.ts](https://github.com/Microsoft/PowerBI-visuals-AttributeSlicer/blob/5e099592097163b5063e471f6821df3af659109d/packages/attribute-slicer-powerbi/src/dataConversion.ts#L103) and [state.ts](https://github.com/Microsoft/PowerBI-visuals-AttributeSlicer/blob/5e099592097163b5063e471f6821df3af659109d/packages/attribute-slicer-powerbi/src/state.ts#L333)

### PR DESCRIPTION
**Pull request by stopyoukid**
- Fixes #76 
- Disables infinite loading because PBI is having weird issues when calling persistProperties quickly in succession.

### CODE REVIEW

File: packages/attribute-slicer-powerbi/src/AttributeSlicerVisual.ts [hunk 1]
```diff
@@ -348,36 +362,90 @@ export default class AttributeSlicer implements powerbi.extensibility.visual.IVi
...
+                let applied = false;
+                const applyFilter = () => {
+                    if (!applied) {
+                        applied = true;
+                        this.host.applyJsonFilter(filter, "general", "filter", action);
+                    }
+                };
+
+                this.afterNextUpdate.then(applyFilter);
+                setTimeout(applyFilter, 300);
```
Comment (eric-kimbrel) [inline packages/attribute-slicer-powerbi/src/AttributeSlicerVisual.ts]: Can you give a quick explanation of the logic here, why set a timeout and have all the logic to apply the filter on the next update if it hasn't been applied already instead of just applying it in this function?
